[package]
name = "uri"
version = "0.5.0"
authors = ["Marli Frost <marli@frost.red>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false, optional = true }

[features]
default = ["std"]
std = []